package online.syncio.backend.messagecontent;

public enum TypeEnum {
    TEXT,
    STICKER,
    IMAGE,
    NOTIFICATION_CREATE_ROOM,
    NOTIFICATION_ADD_MEMBER,
    NOTIFICATION_REMOVE_MEMBER,
    NOTIFICATION_LEAVE_ROOM,
    NOTIFICATION_CHANGE_NAME,
    NOTIFICATION_MAKE_ADMIN,
    NOTIFICATION_REMOVE_ADMIN;
}
